awsRegion: ${aws_region}

autoDiscovery:
  clusterName: ${eks_cluster_name}

image:
  tag: ${image_tag}

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi
%{ if length(node_selectors) > 0 }
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
%{~ for term in node_selectors }
            - key: ${ term.key }
              operator: "In"
              values:
                - ${ term.value }
%{~ endfor }
%{ endif }
